### ISSUE TITLE
[BUG] Null pointer with Mummies

### ISSUE THREAD

**Issue by purrplingcat** [purrplingcat/PurrplingMod#57]
**Describe the bug**
Happens when encountering any level that has mummies if you have an NPC following you, causing continuous log spam and severe slowdown upon entering such levels.

```
System.NullReferenceException: Object reference not set to an instance of an object.
at NpcAdventure.AI.Controller.FightController.IsValidMonster(Monster monster) in C:\Users\Ellen\source\repos\PurrplingMod\NpcAdventure\AI\Controller\FightController.cs:line 172
at NpcAdventure.AI.Controller.FightController.CheckMonsterToFight() in C:\Users\Ellen\source\repos\PurrplingMod\NpcAdventure\AI\Controller\FightController.cs:line 189
at NpcAdventure.AI.Controller.FightController.Update(UpdateTickedEventArgs e) in C:\Users\Ellen\source\repos\PurrplingMod\NpcAdventure\AI\Controller\FightController.cs:line 269
at NpcAdventure.AI.AI_StateMachine.Update(UpdateTickedEventArgs e) in C:\Users\Ellen\source\repos\PurrplingMod\NpcAdventure\AI\AI_StateMachine.cs:line 149
at NpcAdventure.StateMachine.State.RecruitedState.GameLoop_UpdateTicked(Object sender, UpdateTickedEventArgs e) in C:\Users\Ellen\source\repos\PurrplingMod\NpcAdventure\StateMachine\State\RecruitedState.cs:line 204
at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 88
```

Edit: I'm actually using 0.5.0 (from your github release), not 0.4.0, along with SMAPI 3.0.1

Anyway, thanks for your great mod!

**To Reproduce**
1. Go to skullcavern
2. Try NPC fight with Mummy
3. See error

**Expected behavior**
A clear error log, no exceptions and NPC can fight

**Desktop (please complete the following information):**
 - OS: unknown
 - SDV version 1.4
 - SMAPI version 3.0.1
 - Version 0.5.0

---

Reported on Nexusmods https://www.nexusmods.com/stardewvalley/mods/4582/?tab=bugs&issue_id=432865

**Comment by purrplingcat** [comment]
Probably this bug has effect because change in SDV 1.4 API for `reviveTimer`. I will look it evening when I go back home.
